import fs from 'node:fs';
import path from 'node:path';
const root=process.argv[2]||'.janu-live';
const files=fs.readdirSync(root).filter(f=>f.endsWith('.gs')||f.endsWith('.js'));
const target=files.find(f=>{const t=fs.readFileSync(path.join(root,f),'utf8');return t.includes('function verifyReleaseIdentity()')&&t.includes('const P12');});
if(!target)throw new Error('TrackerWorkflow source not found');
const file=path.join(root,target);let s=fs.readFileSync(file,'utf8'),before=s;
const anchor='function verifyReleaseIdentity()';const i=s.indexOf(anchor);if(i<0)throw new Error('release identity anchor missing');
const defs=[
["function nextResumeRevision_(current)",`function nextResumeRevision_(current){const m=String(current||'V1').toUpperCase().match(/V(\\d+)$/);const n=m?Number(m[1])+1:2;return'V'+n;}`],
["function revisionDecision_(ctx)",`function revisionDecision_(ctx){ctx=ctx||{};if(ctx.submitted===true)return{action:'IMMUTABLE_SUBMITTED',allow:false};if(!Array.isArray(ctx.unresolvedComments)||ctx.unresolvedComments.length===0)return{action:'NO_CHANGE',allow:false};return{action:'CREATE_REVISION',allow:true,nextVersion:nextResumeRevision_(ctx.currentVersion||'V1')};}`],
["function classifyJobOutcomeEmail_(msg)",`function classifyJobOutcomeEmail_(msg){msg=msg||{};const t=(String(msg.subject||'')+' '+String(msg.snippet||'')+' '+String(msg.from||'')).toLowerCase();if(/offer|compensation|salary|equity/.test(t))return'OFFER_OR_COMP';if(/rejected|rejection|not moving forward|other candidates/.test(t))return'REJECTION';if(/interview|schedule|calendar|meet with|hiring manager/.test(t))return'INTERVIEW_OR_SCHEDULING';if(/assessment|take[- ]?home|coding test|case study/.test(t))return'ASSESSMENT';if(/received your application|application received|thank you for applying/.test(t))return'APPLICATION_ACK';if(/recruiter|talent acquisition|sourcer/.test(t))return'RECRUITER_REPLY';if(/job alert|new jobs|recommended jobs/.test(t))return'JOB_ALERT';return'UNRELATED';}`],
["function outcomeMatchScore_(email,app)",`function outcomeMatchScore_(email,app){email=email||{};app=app||{};const text=(String(email.subject||'')+' '+String(email.snippet||'')+' '+String(email.from||'')).toLowerCase();let score=0;if(app.company&&text.includes(String(app.company).toLowerCase()))score+=4;if(app.role&&text.includes(String(app.role).toLowerCase()))score+=3;if(app.domain&&text.includes(String(app.domain).toLowerCase()))score+=3;if(app.atsId&&text.includes(String(app.atsId).toLowerCase()))score+=5;if(app.recruiter&&text.includes(String(app.recruiter).toLowerCase()))score+=2;return score;}`],
["function outcomeMatchDecision_(candidates)",`function outcomeMatchDecision_(candidates){candidates=Array.isArray(candidates)?candidates.slice():[];candidates.sort((a,b)=>Number(b.score||0)-Number(a.score||0));if(!candidates.length||Number(candidates[0].score||0)<3)return{action:'NO_MATCH'};if(candidates[1]&&Number(candidates[0].score||0)-Number(candidates[1].score||0)<2)return{action:'AMBIGUOUS',candidateIds:candidates.slice(0,2).map(x=>x.id)};return{action:'MATCH',applicationId:candidates[0].id};}`],
["function contactDiscoveryRoute_(ctx)",`function contactDiscoveryRoute_(ctx){ctx=ctx||{};if(ctx.cachedPublicContacts===true)return'CACHE';if(ctx.officialPublicPage===true)return'DIRECT_OFFICIAL';if(ctx.tavilyAvailable!==false)return'TAVILY';if(ctx.serpApiAvailable!==false)return'SERPAPI';return'UNAVAILABLE';}`],
["function contactCandidateDecision_(ctx)",`function contactCandidateDecision_(ctx){ctx=ctx||{};if(ctx.privateOrPaidOnly===true)return'REJECT_PRIVATE_OR_PAID';if(!ctx.publicUrl)return'REJECT_NO_PUBLIC_SOURCE';if(Number(ctx.confidence||0)<0.5)return'REJECT_LOW_CONFIDENCE';return'ACCEPT_PUBLIC_CANDIDATE';}`],
["function p1cContractSelfTest_()",`function p1cContractSelfTest_(){const c=[];c.push(nextResumeRevision_('V2')==='V3');c.push(revisionDecision_({submitted:true,unresolvedComments:['x']}).action==='IMMUTABLE_SUBMITTED');c.push(revisionDecision_({currentVersion:'V2',unresolvedComments:['x']}).nextVersion==='V3');c.push(classifyJobOutcomeEmail_({subject:'Interview scheduling for Product Manager'})==='INTERVIEW_OR_SCHEDULING');c.push(classifyJobOutcomeEmail_({subject:'Thank you for applying'})==='APPLICATION_ACK');c.push(outcomeMatchDecision_([{id:'A',score:8},{id:'B',score:4}]).applicationId==='A');c.push(outcomeMatchDecision_([{id:'A',score:8},{id:'B',score:7}]).action==='AMBIGUOUS');c.push(contactDiscoveryRoute_({officialPublicPage:true})==='DIRECT_OFFICIAL');c.push(contactCandidateDecision_({publicUrl:'https://example.com',confidence:0.8})==='ACCEPT_PUBLIC_CANDIDATE');if(c.some(x=>!x))throw new Error('P1-C contract self-test failed '+JSON.stringify(c));return{pass:true,total:c.length,contract:'P1-C-1'};}`],
["function runP1CContractSelfTest()",`function runP1CContractSelfTest(){const x=p1cContractSelfTest_();upsertWorkerState_('p1c_self_test',x.pass?'PASS':'FAIL',JSON.stringify(x));upsertWorkerState_('p1c_contract_version','P1-C-1','Revision/Gmail/contact contract telemetry');return x;}`]
];
let block='// P1-C Revision / Gmail outcomes / Contacts contracts\n';for(const [token,code] of defs)if(!s.includes(token))block+=code+'\n';if(block.trim()!=='// P1-C Revision / Gmail outcomes / Contacts contracts')s=s.slice(0,i)+block+'\n'+s.slice(i);
const healthNeedle="try{runP1BContractSelfTest();}catch(e){upsertWorkerState_('p1b_self_test','FAIL',String((e&&e.stack)||e).slice(0,1500));}";
if(s.includes(healthNeedle)&&!s.includes('try{runP1CContractSelfTest();}'))s=s.replace(healthNeedle,healthNeedle+"try{runP1CContractSelfTest();}catch(e){upsertWorkerState_('p1c_self_test','FAIL',String((e&&e.stack)||e).slice(0,1500));}");
for(const token of defs.map(x=>x[0]).concat(['p1c_self_test']))if(!s.includes(token))throw new Error('P1-C contract missing '+token);
if(s!==before)fs.writeFileSync(file,s);
console.log(JSON.stringify({status:'PASS',file:target,changed:s!==before,workstream:'P1-C',telemetry:'p1c_self_test'},null,2));