import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const input=process.argv[2]||'.janu-live',expectedVersion=process.env.EXPECTED_VERSION||'1.3.8',expectedSuite=process.env.EXPECTED_SUITE||'p0-regression-v19';
let files=[];if(fs.existsSync(input)&&fs.statSync(input).isDirectory())files=fs.readdirSync(input).filter(f=>f.endsWith('.gs')||f.endsWith('.js')).sort().map(f=>path.join(input,f));else if(fs.existsSync(input))files=[input];if(!files.length)throw new Error('No Apps Script source');
const text=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');function fail(m){console.error('FAIL: '+m);process.exitCode=1;}
const v=text.match(/P12\s*=\s*Object\.freeze\(\{[\s\S]*?VERSION\s*:\s*'([^']+)'/),q=text.match(/P12\s*=\s*Object\.freeze\(\{[\s\S]*?SUITE\s*:\s*'([^']+)'/),vb=text.match(/function verifyReleaseIdentity\(\)\s*\{([\s\S]*?)\n\}/),rl=text.split('\n').find(x=>x.includes("'RELEASE-001'")),hv=text.match(/\/\/ RELEASE:\s*([^\n]+)/),hs=text.match(/\/\/ REGRESSION SUITE:\s*([^\n]+)/);
if(!v||v[1]!==expectedVersion)fail('P12 VERSION mismatch');if(!q||q[1]!==expectedSuite)fail('P12 SUITE mismatch');if(!hv||hv[1].trim()!==expectedVersion)fail('header VERSION mismatch');if(!hs||hs[1].trim()!==expectedSuite)fail('header SUITE mismatch');if(!vb||!vb[1].includes(`expectedVersion='${expectedVersion}'`)||!vb[1].includes(`expectedSuite='${expectedSuite}'`))fail('verifyReleaseIdentity mismatch');if(!rl||!rl.includes(`P12.VERSION==='${expectedVersion}'`)||!rl.includes(`P12.SUITE==='${expectedSuite}'`))fail('RELEASE-001 mismatch');
for(const t of ['1.3.7','p0-regression-v18','1.3.6','p0-regression-v17','1.3.5','p0-regression-v16','1.3.4','p0-regression-v15','1.3.3','p0-regression-v14'])if(text.includes(t))fail('stale identity '+t);
const fns=[...text.matchAll(/^function\s+([A-Za-z0-9_$]+)\s*\(/gm)].map(m=>m[1]),dup=[...new Set(fns.filter((n,i,a)=>a.indexOf(n)!==i))];if(dup.length)fail('duplicate functions '+dup.join(','));
for(const r of ['PACK-SAN-001','QA-REPAIR-001','BOOTSTRAP-003','BOOTSTRAP-004','BOOTSTRAP-005','BOOTSTRAP-006','BOOTSTRAP-007','BOOTSTRAP-008','CONTROL-001','CONTROL-002','RELEASE-001'])if(!text.includes(r))fail(r+' missing');
for(const t of ["function lockCollisionAction_(triggerCount){return 'SCHEDULE_REPLACEMENT';}",'replacementScheduled:true','function phase1HealthTick(){const op=processOperatorCommand_();if(op)return op;',"function p0PrepareAction_(){return 'DEFER_TO_STRICT_GATES';}",'function enablePreflightMode_(','function closureAwareEnablePreflight_(','function closurePhaseNext_(',"enablePreflightMode_(P_().getProperty('P0_CLOSURE_PHASE'),workerStateValue_('p0_live_preflight'))","p0ClosureState_('REGRESSION','Bounded PREPARE complete; strict gates next')", "closurePhaseNext_('PREPARE')==='REGRESSION'"])if(!text.includes(t))fail('contract missing: '+t);
if(text.includes("upsertWorkerState_('p0_closure_phase','REGRESSION'"))fail('telemetry-only PREPARE transition remains');if(text.includes('enablePreflightMode_(p0ClosureState_(),'))fail('setter still misused as getter');
const sha=crypto.createHash('sha256').update(text).digest('hex');console.log(JSON.stringify({status:process.exitCode?'FAIL':'PASS',expectedVersion,expectedSuite,files:files.map(f=>path.basename(f)),functions:fns.length,sha,fixes:['FL-031','CONTROL-002','FL-033','FL-034','FL-035']},null,2));if(process.exitCode)process.exit(process.exitCode);
